theme = "tokyonight"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
cursorline = false
cursorcolumn = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[keys.normal]
C-s = ":w!"
C-w = ":buffer-close"
C-a = ":reload-all"
C-v = [":clipboard-paste-before"]
C-r = ":fmt"
# C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer_close!", ":theme tokyonight"]
# A-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight_storm"]
# C-f = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight"]

[keys.insert]
C-s = [":w!", "normal_mode"]
C-w = [":buffer-close", "normal_mode"]
C-v = [":clipboard-paste-before"]
